-- phpMyAdmin SQL Dump
-- version 5.0.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Erstellungszeit: 22. Dez 2020 um 11:43
-- Server-Version: 10.4.11-MariaDB
-- PHP-Version: 7.4.3

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Datenbank: `agbm`
--

-- --------------------------------------------------------

--
-- Tabellenstruktur für Tabelle `songs`
--

CREATE TABLE `songs` (
  `id` int(11) NOT NULL,
  `title` varchar(50) NOT NULL,
  `versnr` int(2) NOT NULL,
  `v1` varchar(500) NOT NULL,
  `v2` varchar(500) NOT NULL,
  `v3` varchar(500) NOT NULL,
  `v4` varchar(500) NOT NULL,
  `v5` varchar(500) NOT NULL,
  `v6` varchar(500) NOT NULL,
  `v7` varchar(500) NOT NULL,
  `v8` varchar(500) NOT NULL,
  `v9` varchar(500) NOT NULL,
  `v10` varchar(500) NOT NULL,
  `v11` varchar(500) NOT NULL,
  `v12` varchar(500) NOT NULL,
  `v13` varchar(500) NOT NULL,
  `v14` varchar(500) NOT NULL,
  `v15` varchar(500) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

--
-- Daten für Tabelle `songs`
--

INSERT INTO `songs` (`id`, `title`, `versnr`, `v1`, `v2`, `v3`, `v4`, `v5`, `v6`, `v7`, `v8`, `v9`, `v10`, `v11`, `v12`, `v13`, `v14`, `v15`) VALUES
(1, 'Allein Gott in der Höh', 4, 'Allein Gott in der Höh sei Ehr\r\nund Dank für seine Gnade;\r\ndarum, dass nun und nimmermehr\r\nuns rühren kann kein Schade;\r\nein Wohlgefalln Gott an uns hat,\r\nnun ist groß Fried ohn Unterlass,\r\nall Fehd hat nun ein Ende.', 'Wir beten an und loben dich;\r\nfür deine Ehr wir danken,\r\ndaß du, Gott Vater, ewiglich\r\nregierst ohn alles Wanken.\r\nGanz ohne Maß ist deine Macht;\r\nallzeit geschieht, was du bedacht.\r\nWohl uns des guten Herren!', 'O Jesus Christ, Sohn eingeborn\r\ndes allerhöchsten Vaters,\r\nVersöhner derer, die verlorn,\r\ndu Stiller unsers Haders,\r\nLamm Gottes,  heilger Herr und Gott:\r\nnimm an die Bitt in unsrer Not,\r\nerbarm dich unser aller!', 'O Heilger Geist, du höchstes Gut,\r\nmit deinem Heil uns tröste,\r\nvor Satans Macht nimm uns in Hut,\r\ndie Jesus Christ erlöste\r\ndurch Marter groß und bittern Tod;\r\nwend allen Jammer ab und Not.\r\nDarauf wir uns verlassen.', '', '', '', '', '', '', '', '', '', '', ''),
(2, 'Lobe den Herren', 5, 'Lobe den Herren,\r\nden mächtigen König der Ehren,\r\nmeine geliebete Seele, \r\ndas ist mein Begehren.\r\nKommet zuhauf,\r\nPsalter und Harfe, wacht auf,\r\nlasset den Lobgesang hören!', 'Lobe den Herren,\r\nder alles so herrlich regieret,\r\nder dich auf Adelers \r\nFittichen sicher geführet,\r\nder dich erhält,\r\nwie es dir selber gefällt;\r\nhast du nicht dieses verspüret?', 'Lobe den Herren,\r\nder künstlich und fein dich bereitet,\r\nder dir Gesundheit verliehen,\r\ndich freundlich geleitet.\r\nIn wieviel Not\r\nhat nicht der gnädige Gott\r\nüber dir Flügel gebreitet.', 'Lobe den Herren,\r\nder deinen Stand sichtbar gesegnet,\r\nder aus dem Himmel\r\nmit Strömen der Liebe geregnet.\r\nDenke daran,\r\nwas der Allmächtige kann,\r\nder dir mit Liebe begegnet.', 'Lobe den Herren,\r\nwas in mir ist, lobe den Namen.\r\nAlles, was Odem hat,\r\nlobe mit Abrahams Samen.\r\nEr ist dein Licht,\r\nSeele, vergiss es ja nicht;\r\nlob ihn in Ewigkeit! Amen!', '', '', '', '', '', '', '', '', '', ''),
(3, 'Singet dem Herrn ein neues Lied', 1, 'Singet dem Herrn ein neues Lied,\r\nsinget mit Freuden, mit Freuden vom Sieg!\r\n\r\nSinget dem Herrn ein neues Lied,\r\nsinget mit Freuden, mit Freuden vom Sieg!\r\n\r\n', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(4, 'Du meine Seele, singe', 7, 'Du meine Seele, singe, \r\nwohlauf und singe schön\r\ndem, welchem alle Dinge\r\nzu Dienst und Willen stehn!\r\nIch will den Herren droben\r\nhier preisen auf der Erd;\r\nich will ihn herzlich loben,\r\nsolang ich leben werd.', 'Wohl dem, der einzig schauet\r\nnach Jakobs Gott und Heil!\r\nWer dem sich anvertrauet,\r\nder hat das beste Teil,\r\ndas höchste Gut erlesen,\r\nden schönsten Schatz geliebt;\r\nsein Herz und ganzes Wesen\r\nbleibt ewig unbetrübt.', 'Hier sind die starken Kräfte,\r\ndie unerschöpfte Macht;\r\ndas weisen die Geschäfte,\r\ndie seine Hand gemacht:\r\nDer Himmel und die Erde\r\nmit ihrem ganzen Heer,\r\nder Fisch unzählge Herde\r\nim großen, wilden Meer.', 'Hier sind die treuen Sinnen,\r\ndie niemand Unrecht tun,\r\nall denen Gutes gönnen,\r\ndie in der Treu beruhn.\r\nGott hält sein Wort mit Freuden,\r\nund was er spricht, geschicht,\r\nund wer Gewalt muss leiden,\r\nden schützt er im Gericht.', 'Er weiß viel tausend Weisen,\r\nzu retten aus dem Tod,\r\nernährt und gibet Speisen\r\nzur Zeit der Hungersnot,\r\nmacht schöne rote Wangen\r\noft bei geringem Mahl,\r\nund die da sind gefangen,\r\ndie reißt er aus der Qual.', 'Er ist das Licht der Blinden,\r\nerleuchtet ihr Gesicht,\r\nund die sich schwach befinden,\r\ndie stellt er aufgericht‘.\r\nEr liebet alle Frommen,\r\nund die ihm günstig seind,\r\ndie finden, wenn sie kommen,\r\nan ihm den besten Freund.', 'Ach ich bin viel zu wenig,\r\nzu rühmen seinen Ruhm;\r\nder Herr allein ist König,\r\nich eine welke Blum. \r\nJedoch weil ich gehöre\r\ngen Zion in sein Zelt,\r\nist‘s billig, dass ich mehre\r\nsein Lob vor aller Welt.', '', '', '', '', '', '', '', ''),
(5, 'Großer Gott, wir loben dich!', 8, 'Großer Gott, wir loben dich!\r\nHerr, wir preisen deine Stärke.\r\nVor dir beugt die Erde sich\r\nund bewundert deine Werke.\r\nWie du warst vor aller Zeit,\r\nso bleibst du in Ewigkeit.', 'Alles, was dich Preisen kann,\r\nCherubim und Seraphinen,\r\nstimmen dir ein Loblied an;\r\nalle Engel, die dir dienen,\r\nRufen dir stets ohne Ruh:\r\nHeilig, heilig, heilig! zu. ', 'Heilig, Herr Gott Zebaoth,\r\nheilig, Herr der Engelheere!\r\nStarker Helfer in der Not;\r\nHimmel, Erde, Luft und Meere\r\nsind erfüllt von deinem Ruhm;\r\nalles ist dein Eigentum.', 'Auf dem ganzen Erdenkreis\r\nloben Große und auch Kleine\r\ndich, Gott Vater. Dir zum Preis\r\nsingt die heilige Gemeinde; \r\nsie verehrt auf seinem Thron\r\ndeinen eingeborenen Sohn. ', 'Sie verehrt den Heiligen Geist,\r\nwelcher uns mit seinen Lehren\r\nund mit Trost kräftig speist,\r\nder , o König aller Ehren,\r\nder mit dir, Herr Jesus Christ,\r\nund dem Vater ewig ist.', 'Du, des Vaters ewger Sohn,\r\nhast die Menschheit angenommen.\r\nDu bist auch von deinem Thron\r\nzu uns auf die Welt gekommen.\r\nGnade hast du uns gebracht,\r\nvon der Sünde frei gemacht.', 'Nun mehr steht das Himmelstor\r\nallen, welche glauben, offen.\r\nDu stellst uns den Vater vor,\r\nwenn wir kindlich auf dich hoffen.\r\nEndlich kommst du zum Gericht;\r\nZeit und Stunde weiß man nicht.', 'Herr, erbarm, erbarme dich!\r\nAuf uns komme, Herr, dein Segen!\r\nDeine Güte zeige sich\r\nallen der Verheißung wegen!\r\nAuf dich hoffen wir allein,\r\nLass uns nicht verloren sein!', '', '', '', '', '', '', ''),
(6, 'Dir, dir, o Höchster, will ich singen', 6, 'Dir, dir, o Höchster, will ich singen;\r\ndenn wo ist doch ein solcher Gott wie du?\r\nDir will ich meine Lieder bringen;\r\nach gib mir deines Geistes Kraft dazu,\r\ndass ich es tu im Namen Jesu Christ,\r\nso wie es dir durch ihn gefällig ist.', 'Zieh mich, o Vater, zu dem Sohne,\r\ndamit dein Sohn mich wieder zieh zu dir.\r\nDein Geist in meinem Herzen wohne\r\nund meine Sinne und Verstand regier,\r\ndass ich den Frieden Gottes schmeck und fühl\r\nund dir darob im Herzen sing und spiel.', 'Verleih mir, Höchster, solche Güte,\r\nso wird gewiss mein Singen recht getan;\r\nso klingt es schön in meinem Liede,\r\nund ich bet dich in Geist und Wahrheit an;\r\nso hebt dein Geist mein Herz zu dir empor,\r\ndass ich dir Psalmen sing im höhern Chor.', 'Dein Geist kann mich bei dir vertreten\r\nmit Seufzern, die ganz unaussprechlich sind;\r\nder lehret mich recht gläubig beten,\r\ngibt Zeugnis meinem Geist, dass ich dein Kind\r\nund ein Miterbe Jesu Christi sei,\r\ndaher ich: Abba, lieber Vater! schrei.', 'Wohl mir, dass ich dies Zeugnis habe!\r\nDrum bin ich voller Trost und Freudigkeit\r\nund weiß, du gibst mir jede Gabe,\r\ndie jetzt und ewig mir zum Heil gedeiht.\r\nJa, Vater, du tust überschwenglich mehr,\r\nals ich verstehe, bitte und begehr.', 'Wohl mir, ich bitt in Jesu Namen,\r\nder mich zu deiner Rechten selbst vertritt;\r\nin ihm ist alles Ja und Amen,\r\nwas ich von dir im Geist und Glauben bitt.\r\nWohl mir, Lob dir jetzt und in Ewigkeit,\r\ndass du mir schenktest solche Seligkeit.', '', '', '', '', '', '', '', '', ''),
(7, 'Lob Gott getrost mit Singen', 4, 'Lob Gott getrost mit Singen,\r\nfrohlock, du christlich Schar!\r\nDir soll es nicht misslingen,\r\nGott hilft dir immerdar.\r\nOb du gleich hier musst tragen\r\nviel Widerwärtigkeit,\r\ndoch sollst du nicht verzagen,\r\ner hilft aus allem Leid.', 'Kann und mag auch verlassen\r\nein Mutter je ihr Kind\r\nund also gar verstoßen, \r\ndass es kein Gnad mehr findt?\r\nUnd ob sich‘s möcht begeben,\r\ndass sie sogar abfiel:\r\nGott schwört bei seinem Leben,\r\ner dich nicht lassen will.', 'Darum lass dich nicht schrecken,\r\no du christgläubge Schar!\r\nGott wird dir Hilf erwecken\r\nund selbst dein nehmen wahr:\r\nhat er dich doch gezeichnet,\r\ngegraben in sein Händ,\r\ndein Nam stets vor ihm leuchtet,\r\ndass er die Hilfe sendt.', 'Gott solln wir allzeit loben,\r\nder sich aus großer Gnad\r\ndurch seine milden Gaben\r\nuns kundgegeben hat.\r\nEr wird uns auch erhalten\r\nin Lieb und Einigkeit\r\nund unser freundlich walten\r\nhier und in Ewigkeit.', '', '', '', '', '', '', '', '', '', '', ''),
(22, 'Sei Lob und Ehr dem höchsten Gut', 7, 'Sei Lob und Ehr dem höchsten Gut,\r\ndem Vater aller Güte,\r\ndem Gott, der alle Wunder tut,\r\ndem Gott, der mein Gemüte\r\nmit seinem reichen Trost erfüllt,\r\ndem Gott, der allen Jammer stillt.\r\nGebt unserm Gott die Ehre!', 'Es danken dir die Himmelsheer,\r\no Herrscher aller Thronen,\r\nund die auf Erden, Luft und Meer\r\nin deinem Schatten wohnen,\r\ndie preisen deine Schöpfermacht,\r\ndie alles also wohl bedacht.\r\nGebt unserm Gott die Ehre!', 'Was unser Gott geschaffen hat,\r\ndas will er auch erhalten,\r\ndarüber will er früh und spat\r\nmit seiner Gnade walten.\r\nIn seinem ganzen Königreich\r\nist alles recht und alles gleich.\r\nGebt unserm Gott die Ehre!', 'Ich rief zum Herrn in meiner Not:\r\nAch Gott, vernimm mein Schreien!\r\nDa half mein Helfer mir vom Tod\r\nund ließ mir Trost gedeihen.\r\nDrum dank, ach Gott, drum dank ich dir;\r\nach danket, danket Gott mit mir!\r\nGebt unserm Gott die Ehre!', 'Ich will dich all mein Leben lang,\r\no Gott, von nun an ehren.\r\nMan soll, Gott, deinen Lobgesang\r\nan allen Orten hören.\r\nMein ganzes Herz ermuntre sich,\r\nmein Geist und Leib erfreue dich!\r\nGebt unserm Gott die Ehre!', 'Ihr, die ihr Christi Namen nennt,\r\ngebt unserm Gott die Ehre!\r\nIhr, die ihr Gottes Macht bekennt,\r\ngebt unserm Gott die Ehre!\r\nDie falschen Götzen macht zu Spott;\r\nder Herr ist Gott, der Herr ist Gott!\r\nGebt unserm Gott die Ehre!', 'Gebt unserm Gott die Ehre!\r\nSo kommet vor sein Angesicht\r\nmit jauchzenvollem Springen;\r\nbezahlet die gelobte Pflicht\r\nund lasst uns fröhlich singen:\r\nGott hat es alles wohl bedacht\r\nund alles, alles recht gemacht.\r\nGebt unserm Gott die Ehre!', '', '', '', '', '', '', '', ''),
(31, 'Danket dem Herrn! ', 6, 'Danket dem Herrn! \r\nWir danken dem Herrn;\r\nDenn er ist freundlich,\r\nund seine Güte währet ewiglich,\r\nsie währet ewiglich,\r\nsie währet ewiglich.', 'Lobet den Herrn!\r\nJa, lobe den Herrn,\r\nauch meine Seele, \r\nvergiss es nie, was er dir Guts getan,\r\nwas er dir Guts getan,\r\nwas er die Guts getan.', 'Sein ist die Macht!\r\nAllmächtig ist Gott,\r\nsein Tun ist weise\r\nund seine Huld ist jeden Morgen neu,\r\nist jeden Morgen neu,\r\nist jeden Morgen neu.', 'Groß ist der Herr!\r\nJa groß ist der Herr;\r\nsein Nam ist heilig,\r\nund alle Welt ist seiner Ehre voll,\r\nist seiner Ehre voll,\r\nist seiner Ehre voll.', 'Betet ihn an!\r\nAnbetung dem Herrn!\r\nMit hoher Ehrfurcht\r\nwerd auch von uns sein Name stets genannt,\r\nsein Name stets genannt,\r\nsein Name stets genannt.', 'Singet dem Herrn!\r\nLobsinget dem Herrn\r\nin frohen Chören,\r\ndenn er vernimmt auch unsern Lobgesang,\r\nauch unsern Lobgesang,\r\nauch unsern Lobgesang!', '', '', '', '', '', '', '', '', ''),
(36, 'Gott ist gegenwärtig', 7, 'Gott ist gegenwärtig. \r\nLasset uns anbeten\r\nund in Ehrfurcht vor ihn treten.\r\nGott ist in der Mitten.\r\nAlles in uns schweige\r\nund sich innigst vor ihm beuge.\r\nWer ihn kennt, wer ihn nennt,\r\nschlag die Augen nieder,\r\nkommt, ergebt euch wieder.', 'Gott ist gegenwärtig, \r\ndem die Cherubinen\r\nTag und Nacht gebücket dienen.\r\nHeilig, heilig, heilig! \r\nSingen ihm zur Ehre\r\naller Engel hohe Chöre.\r\nHerr, vernimm unsre Stimm,\r\nda auch wir Geringen\r\nunsre Opfer bringen.', 'Wir entsagen willig \r\nallen Eitelkeiten,\r\naller Erdenlust und Freuden;\r\nda liegt unser Wille, \r\nSeele, Leib und Leben\r\ndir zum Eigentum ergeben.\r\nDu allein sollst es sein,\r\nunser Gott und Herre,\r\ndir gebührt die Ehre.', 'Majestätisch Wesen, möcht ich recht dich preisen\r\nund im Geist dir Dienst erweisen!\r\nMöcht ich wie die Engel immer vor dir stehen\r\nund dich gegenwärtig sehen!\r\nLass mich dir für und für\r\ntrachten zu gefallen,\r\nliebster Gott, in allem.', 'Du durchdringest alles; lass dein schönstes Lichte,\r\nHerr, berühren mein Gesichte.\r\nWie die zarten Blumen willig sich entfalten\r\nund der Sonne stille halten,\r\nlass mich so, still und froh\r\ndeine Strahlen fassen\r\nund dich wirken lassen.', 'Mache mich einfältig, innig, abgeschieden,\r\nsanft und still in deinem Frieden.\r\nMach mich reines Herzens, dass ich deine Klarheit\r\nschauen mag in Geist und Wahrheit.\r\nLass mein Herz himmelwärts\r\nwie ein Adler schweben\r\n und in dir nur leben.', 'Herr, komm in mir wohnen, lass mein Herz auf Erden\r\ndir ein Heiligtum noch werden.\r\nKomm, du nahes Wesen, dich in mir verkläre,\r\ndass ich dich stets lieb und ehre.\r\nWo ich geh, sitz und steh,\r\nlass mich dich erblicken\r\nund vor dir mich bücken.', '', '', '', '', '', '', '', ''),
(51, 'Heilig, heilig, heilig', 3, 'Heilig, heilig, heilig, ewiger Vater!\r\nFrühe künden Lieder von deiner Herrlichkeit.\r\nHeilig, heilig, heilig, Helfer und Berater!\r\nGott, der du warst und bleibst in Ewigkeit.', 'Heilig, heilig, heilig! Engel sich neigen,\r\nlegen ihre Kronen zu deinen Füßen hin.\r\nTausend, aber Tausend ehrfurchtsvoll sich beugen,\r\ndenn, Gott, dein Stuhl besteht von Anbeginn.\r\n', 'Heilig, heilig, heilig! Dunkel verhüllt dich,\r\nMenschenauge kann deines Thrones Glanz\r\nnicht sehn.\r\nDu allein bist heilig, Ewig und unendlich;\r\nGott, deine Macht, dein Lieben bleibt\r\nbestehn.', '', '', '', '', '', '', '', '', '', '', '', ''),
(60, 'Jesus, meine Sonne', 4, 'Jesus, meine Sonne, \r\nin der dunklen Nacht,\r\nJesus, meine Wonne, \r\nwenn mir Freude lacht.\r\nJesus, meine Liebe, \r\ndu mein einzig Glück,\r\nnimmer wend ich wieder \r\nvon dir weg den Blick.', 'Du hast meine Seele\r\nwunderbar erquickt,\r\ndeines Geistes Siegel\r\ntief mir eingedrückt.\r\nDeinen süßen Frieden\r\nschmeck ich täglich nun,\r\ndarf in deiner Liebe\r\nStund um Stunde ruhn.', 'In der Welt Gedränge,\r\nin der Sünde Streit\r\nsind, Herr, deine Siege\r\nstets für mich bereit.\r\nDu willst für mich kämpfen,\r\nich darf stille sein,\r\nmich in deine Gnade\r\nhüllen fester ein.', 'Welch ein selig Leben\r\nin der dunklen Welt!\r\nFröhlich darf ich jauchzen,\r\nweil mich Jesus hält.\r\nniemand kann mich reißen,\r\nHerr, aus deiner Hand,\r\nbis du mich aus Gnaden\r\nbringst ins Heimatland.', '', '', '', '', '', '', '', '', '', '', ''),
(66, 'Stern, auf den ich schaue', 4, 'Stern, auf den ich schaue,\r\nFels, auf dem ich steh,\r\nFührer, dem ich traue,\r\nStab, an dem ich geh,\r\nBrot, von dem ich lebe,\r\nQuell, an dem ich ruh,\r\nZiel, das ich erstrebe,\r\nalles, Herr, bist du!', 'Ohne dich, wo käme\r\nKraft und Mut mir her?\r\nOhne dich, wer nähme\r\nmeine Bürde, wer?\r\nOhne dich zerstieben\r\nwürden mir im Nu\r\nGlauben, Hoffen, Lieben;\r\nalles, Herr, bist du.', 'Du, nur du bist Wahrheit,\r\nLicht und Leben mir,\r\ngnadenvolle Klarheit\r\nkommt allein von dir.\r\nLass mich Treue halten\r\njetzt und immerzu.\r\nEins nur lass ich walten:\r\nAlles, Herr, bist du!', 'Nun, so will ich wallen\r\nmeinen Pfad dahin,\r\ndir nur zu gefallen,\r\nbis daheim ich bin.\r\nDann mit neuem Singen\r\njauchz ich froh dir zu,\r\nnichts hab ich zu bringen,\r\nalles, Herr, bist du!', '', '', '', '', '', '', '', '', '', '', ''),
(92, 'Teures Wort aus Gottes Munde', 5, 'Teures Wort aus Gottes Munde,\r\ndas mir lauter Segen trägt,\r\ndich allein hab ich zum Grunde\r\nmeiner Seligkeit gelegt;\r\nin dir treff ich alles an,\r\nwas zu Gott mich führen kann.', 'Geist der Gnaden, der im Worte\r\nmich an Gottes Herze legt,\r\nöffne mir des Himmels Pforte,\r\ndass mein Geist hier recht erwägt,\r\nwelche Schätze Gottes Hand\r\ndurch sein Wort ihm zugesandt.', 'Was ich lese, lass mich merken;\r\nwas du sagest, lass mich tun.\r\nWird dein Wort den Glauben stärken,\r\nlass es nicht dabei beruhn,\r\nsondern gib, dass auch dabei\r\nihm das Leben ähnlich sei.', 'Hilf, dass alle meine Wege\r\nnur nach dieser Richtschnur gehn;\r\nwas ich hier zum Grunde lege,\r\nmüsse wie ein Felsen stehn,\r\ndass mein Geist auch Rat und Tat\r\nin den größten Nöten hat.', 'Lass dein Wort mir einen Spiegel,\r\nJesus nachzufolgen, sein.\r\nDrücke drauf ein Gnadensiegel,\r\nschließ den Schatz im Herzen ein,\r\ndass ich fest im Glauben steh,\r\nbis ich dort zum Schauen geh.', '', '', '', '', '', '', '', '', '', ''),
(93, 'Herr, dein Wort, die edle Gabe', 2, 'Herr, dein Wort, die edle Gabe, \r\ndiesen Schatz erhalte mir; \r\ndenn ich zieh es aller Habe \r\nund dem größten Reichtum für. \r\nWenn dein Wort nicht mehr soll gelten, \r\nworauf soll der Glaube ruhn? \r\nMir ist\'s nicht um tausend Welten, \r\naber um dein Wort zu tun.', 'Halleluja! Ja und Amen! \r\nHerr, du wollest auf mich sehn, \r\ndass ich mög in deinem Namen \r\nfest bei deinem Worte stehn. \r\nLass mich eifrig sein beflissen \r\ndir zu dienen früh und spat, \r\nund zugleich zu deinen Füßen \r\nsitzen, wie Maria tat.', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(95, 'Wohl denen, die dein Zeugnis halten ', 3, 'Wohl denen, die dein Zeugnis halten \r\nund suchen dich in deinem Wort,\r\ndem Wort, das niemals wird veralten,\r\ndas sich bewähret fort und fort.\r\nWenn Erd und Himmel auch vergehn,\r\nso bleibet doch das Wort bestehn.', 'Du lässest auf dies Wort mich hoffen,\r\ndas deine Hilfe mir verspricht.\r\nDu zeigst in ihm dein Herz mir offen,\r\nvoll Gnade, Wahrheit, Trost und Licht;\r\nso stärkst du dadurch das Vertraun,\r\nauf dich allein mein Heil zu baun.', 'Erquicke mich auf deinem Wege,\r\nden du mich führst nach deinem Wort.\r\nO nimm mich, Herr, in deine Pflege,\r\nund sei du meines Lebens Hort;\r\nwird doch in keinem andern Heil\r\nund Seligkeit mir je zuteil.', '', '', '', '', '', '', '', '', '', '', '', ''),
(101, 'O Wort aus Gottes Mund', 3, 'O Wort aus Gottes Mund!\r\nNoch nie genug erwägt,\r\ndich hab ich mir allein zum Grund\r\nder Seligkeit gelegt.', 'Du bist mein größter Schatz\r\nund sollst mein Führer sein,\r\nbis ich viel Lebensfrüchte bring\r\nin deinem Gnadenschein.', 'Hilf, dass mein Lebensweg\r\nnach dieser Richtschnur geh,\r\ndass ich beim Spiegel deines Worts,\r\nsolang ich lebe, steh.', '', '', '', '', '', '', '', '', '', '', '', ''),
(106, 'Wohl denen, die da wandeln ', 3, 'Wohl denen, die da wandeln \r\nvor Gott in Heiligkeit, \r\nnach seinem Worte handeln \r\nund leben allezeit, \r\ndie recht von Herzen suchen Gott \r\nund seine Zeugnis\' halten, \r\nsind stets bei ihm in Gnad.', 'Von Herzensgrund ich spreche: \r\nDir sei Dank allezeit, \r\nweil du mich lehrst die Rechte \r\ndeiner Gerechtigkeit. \r\nDie Gnad auch ferner mir gewähr; \r\nich will dein Rechte halten, \r\nVerlass mich nimmermehr.', 'Dein Wort, Herr, nicht vergehet, \r\nes bleibet ewiglich,\r\nso weit der Himmel gehet, \r\nder stets beweget sich; \r\ndein Wahrheit bleibt zu aller Zeit \r\ngleichwie der Grund der Erden, \r\ndurch deine Hand bereit\'. ', '', '', '', '', '', '', '', '', '', '', '', ''),
(108, 'Heilig sei uns, großer Gott', 4, 'Heilig sei uns, großer Gott,\r\nstets dein Wille, dein Gebot;\r\nzum Gehorsam gib uns Kraft,\r\ndeinen Geist, der Liebe schafft.', 'Dein Gesetz sei uns das Licht;\r\nunsrem Geist ermangle nicht\r\ndeines Rates Sicherheit,\r\nleite ihn zur Seligkeit.', 'Unsrer Sünden bittre Not\r\nzeige dein Gesetz, Herr Gott;\r\ndein Erbarmen, deine Gnad\r\nführ uns auf den rechten Pfad.', 'Unser Vorbild sei dein Sohn!\r\nDein Gesetz erfülle schon\r\nunser Herz in dieser Zeit\r\nund in alle Ewigkeit.', '', '', '', '', '', '', '', '', '', '', ''),
(148, 'O du Liebe meiner Liebe', 6, 'O du Liebe meiner Liebe, \r\ndu erwünschte Seligkeit, \r\ndie du dich aus höchstem Triebe \r\nin das jammervolle Leid \r\ndeines Leidens mir zugute \r\nals ein Opfer eingestellt \r\nund bezahlt mit deinem Blute \r\nalle Missetat der Welt.', 'Liebe, die mit Schweiß und Tränen \r\nan dem Ölberg sich betrübt, \r\nLiebe, die mit Blut und Sehnen \r\nunaufhörlich fest geliebt, \r\nLiebe, die mit allem Willen \r\nGottes Zorn und Eifer trägt, \r\nden sonst niemand konnte stillen, \r\nhat dein Sterben hingelegt.', 'Liebe, die mit starkem Herzen \r\nalle Schmach und Hohn gehört, \r\nLiebe, die nicht Angst und Schmerzen \r\nnoch der strenge Tod versehrt, \r\nLiebe, die sich liebend zeiget, \r\nals sich Kraft und Atem endt, \r\nLiebe, die sich liebend neiget,\r\nals sich Leib und Geist getrennt.', 'Liebe, die mit ihren Armen \r\nmich zuletzt umfangen wollt, \r\nLiebe, die aus Liebserbarmen \r\nmich zuletzt in höchster Huld \r\nihrem Vater überlassen, \r\ndie selbst sterbend für mich bat, \r\nmir die Strafe zu erlassen, \r\nweil mich ihr Verdienst vertrat.', 'Liebe, die für mich gestorben \r\nund ein immerwährend Gut \r\nan dem Kreuzesholz erworben, \r\nach wie denk ich an dein Blut! \r\nAch wie dank ich deinen Wunden, \r\ndu verwundte Liebe du, \r\nwenn ich in den letzten Stunden \r\nsanft an deinem Herzen ruh!', 'Liebe, die sich tot gekränket \r\nund für mein erkaltet Herz \r\nin ein kaltes Grab gesenket, \r\nach wie dank ich deinem Schmerz! \r\nHabe Dank, dass du gestorben, \r\ndass ich ewig leben kann, \r\nund der Seele Heil erworben: \r\nNimm mich ewig liebend an!', '', '', '', '', '', '', '', '', ''),
(180, 'Toben auch Stürme, der Herr kennt die Seinen', 5, 'Toben auch Stürme, der Herr kennt die Seinen,\r\nnichts bleibt verborgen, was Jesus nicht sieht.\r\nBald wird sein Zeichen am Himmel erscheinen:\r\nChristus wird siegen, was immer geschieht!\r\nChristus wird siegen, was immer geschieht!', 'Alle Gewaltensind ihm übergeben.\r\nEr ist der Herr,welchem keiner entflieht.\r\nWenn sich auch gegenihn viele erheben:\r\nChristus wird siegen,was immer geschieht!\r\nChristus wird siegen,was immer geschieht!', 'Wird er verworfenund wird er verspottet,\r\nweil die Verheißungso lange verzieht;\r\nwird auch so manchesim Frevel vergottet:\r\nChristus wird siegen,was immer geschieht!\r\nChristus wird siegen,was immer geschieht!', 'Sein ist die Zukunftund sein ist die Erde,\r\ner wirkt hindurchbis ins letzte Gebiet.\r\nFürchte dich nicht,du umgeiferte Herde:\r\nChristus wird siegen,was immer geschieht!\r\nChristus wird siegen,was immer geschieht!', 'Ewige Freudehat er dir beschieden,\r\nJubel ins Herz,auf die Lippen ein Lied.\r\nHeute schon kannstdu‘s erleben im Frieden:\r\nChristus wird siegen,was immer geschieht!\r\nChristus wird siegen,was immer geschieht!', '', '', '', '', '', '', '', '', '', ''),
(206, 'Vater, lass mich Gnade finden', 6, 'Vater, lass mich Gnade finden,\r\ntröste wieder meinen Sinn, \r\nder ich wegen meiner Sünden\r\nso betrübt und traurig bin. \r\nSiehe, mein Gott, wie ich hier \r\njetzt vor deiner Gnadentür \r\nmit dem Zöllner schamrot stehe \r\nund dich um Vergebung flehe.', 'Du bist heilig, ich hingegen \r\nvoller Ungerechtigkeit, \r\nmuss mich bloß aufs Bitten legen \r\nund auf deine Gütigkeit \r\nsetzen meine Zuversicht; \r\ndenn so du, Herr, dein Gericht \r\nließest ohne Gnad ergehen, \r\nwürd es übel um mich stehen. ', 'Aber ach, nach deiner Lehre \r\nwillst du keines Sünders Tod,\r\nsondern dass er sich bekehre\r\nund frei werde seiner Not.\r\nDieser Trost erquicket mich,\r\nder ich weine bitterlich, \r\nweil ich Reu und Leid empfinde\r\nüber meine schwere Sünde.', 'Denke, dass dein Sohn auf Erden\r\ndrum vergossen hat sein Blut, \r\nauf dass könne selig werden, \r\nwer im Glauben Buße tut. \r\nAuch sein Kreuz und Dornenkron \r\nbring ich hier vor deinen Thron; \r\nseinen Tod und Blutvergießen \r\nlass mich Armen auch genießen.', 'Großer Gott von Lieb und Treue, \r\nlass durch Jesu Wunden doch \r\nmeine späte Buß und Reue \r\nvor dir etwas gelten noch. \r\nDenke doch nicht weiter dran, \r\nwas ich habe mißgetan, \r\nlass mein armes Sündenleben \r\nmir aus Gnaden sein vergeben.', 'Willst du nun mir armen Sünder,\r\nmein Gott, barmherzig sein,\r\nIn die Zahl auch deiner Kinder\r\nwiederum mich nehmen ein, \r\nso will ich von Herzen dich\r\ndafür preisen ewiglich.\r\nDrum in Jesu Christi Namen\r\nWollst du mich erhören! Amen.', '', '', '', '', '', '', '', '', ''),
(209, 'So wie ich bin, ohn alle Zier', 6, 'So wie ich bin, ohn alle Zier,\r\nkomm ich, Herr, durch dein Blut zu dir;\r\ndu rufst mir von des Kreuzes Stamm:\r\nSo komme ich, o Gotteslamm!', 'So wie ich bin, so arm und blind,\r\nam Guten leer und voll von Sünd,\r\nbedrückt von Reu und tiefer Scham:\r\nSo komme ich, o Gotteslamm!\r\n', 'So wie ich bin, nimmst du mich an,\r\nwillst mich verlornes Kind empfahn,\r\nvergibst die Schuld, stillst meinen Gram:\r\nSo komme ich, o Gotteslamm!', 'So wie ich bin - Herr, deine Lieb,\r\ndie dich für uns ans Fluchholz trieb,\r\nverstieß noch keinen, der da kam:\r\nSo komme ich, o Gotteslamm!', 'So wie ich bin, so fass ich Mut\r\nund komme auf des Lammes Blut,\r\ndas meine Sünden auf sich nahm:\r\nSo komme ich, o Gotteslamm!', 'So wie ich bin, hast du mich nun.\r\nIn deinen Wunden will ich ruhn,\r\nim Frieden unterm Kreuzesstamm:\r\nSo komme ich, o Gotteslamm!', '', '', '', '', '', '', '', '', ''),
(212, 'Der Tod ist unsrer Sünde Sold', 3, 'Der Tod ist unsrer Sünde Sold. \r\nEr hält uns fest umschlungen. \r\nDoch wer an Jesus Christus glaubt, \r\nist hier und jetzt schon aus dem Tod \r\nzum Leben durchgedrungen.', 'Am Kreuz hat Jesus unsern Tod \r\ndurch seinen Tod bezwungen, \r\nund wer auf Jesus Christus hofft, \r\nist hier und jetzt schon aus dem Tod \r\nzum Leben durchgedrungen.', 'Wo Gottes Geist im Herzen wirkt, \r\nsingt man mit neuen Zungen. \r\nDenn wer mit Jesus Christus lebt, \r\nist hier und jetzt schon aus dem Tod \r\nzum Leben durchgedrungen.', '', '', '', '', '', '', '', '', '', '', '', ''),
(217, 'Ich freu mich in dem Herren ', 4, 'Ich freu mich in dem Herren \r\naus meines Herzens Grund, \r\nbin fröhlich Gott zu Ehren \r\njetzt und zu aller Stund. \r\nMit Freuden will ich singen \r\nzu Lob dem Namen sein; \r\nganz lieblich soll erklingen \r\nein neues Lied allein.', 'In Sünd war ich verloren, \r\nsündlich war all mein Tun.\r\nNun bin ich neu geboren \r\nin Christus, Gottes Sohn. \r\nDer hat mir Heil erworben \r\ndurch seinen bittern Tod, \r\nweil er am Kreuz gestorben \r\nfür meine Missetat.', 'All Sünd ist nun vergeben \r\nund zugedecket fein, \r\ndarf mich nicht mehr beschämen \r\nvor Gott, dem Herren mein. \r\nIch bin ganz neu geschmücket \r\nmit einem schönen Kleid, \r\ngezieret und gesticket \r\nmit Heil und G\'rechtigkeit.', 'Dafür will ich ihm sagen \r\nLob und Dank allezeit,\r\nmit Freud und Ehren tragen \r\ndies köstliche Geschmeid,\r\nwill damit herrlich prangen \r\nvor Gottes Majestät, \r\nhoff darin zu erlangen \r\ndie ewge Seligkeit.', '', '', '', '', '', '', '', '', '', '', ''),
(222, 'Glauben heißt: die Gnad erkennen', 5, 'Glauben heißt: die Gnad erkennen,\r\ndie den Sünder selig macht,\r\nJesus meinen Heiland nennen,\r\nder auch mir das Heil gebracht.', 'Glauben heißt: den Heiland nehmen,\r\nden uns Gott vom Himmel gibt,\r\nsich vor ihm nicht knechtisch schämen,\r\nweil er ja die Sünder liebt.', 'Glauben heißt: der Gnade trauen,\r\ndie uns Jesu Wort verspricht,\r\nda verschwindet Furcht und Grauen\r\ndurch das süße Glaubenslicht.', 'Denn der Glaube tilgt die Sünden,\r\nwäscht sie ab durch Christi Blut\r\nund lässt uns Vergebung finden;\r\nalles macht der Glaube gut.', 'Darum glaubt und fleht um Glauben,\r\nbis ihr fest gegründet seid,\r\nniemand könn ihn euch mehr rauben,\r\nihr habt Gnad und Seligkeit.', '', '', '', '', '', '', '', '', '', ''),
(228, 'Welch Glück ist‘s, erlöst zu sein', 3, 'Welch Glück ist‘s, erlöst zu sein,\r\nHerr, durch dein Blut!\r\nIch tauche mich tief hinein\r\nin diese Flut.\r\nVon Sünd und Unreinigkeit\r\nbin ich hier frei\r\nund jauchze voll selger Freud:\r\nJesus ist treu!\r\nO preist seiner Liebe Macht!\r\nPreist seiner Liebe Macht!\r\nPreist seiner Liebe Macht,\r\ndie uns erlöst!', 'Welch Glück ist‘s, erlöst zu sein,\r\nHerr, durch dein Blut!\r\nIch leide nicht länger Pein,\r\nhabe nun Mut;\r\nmir ging ja ein neues Licht\r\ngnadenvoll auf,\r\ndrum zweifle ich ferner nicht\r\nin meinem Lauf.\r\nO preist seiner Liebe Macht!\r\nPreist seiner Liebe Macht!\r\nPreist seiner Liebe Macht,\r\ndie uns erlöst!', 'O Jesu, Gekreuzigter,\r\ndir jauchz ich zu!\r\nMein Heiland, mein Gott und Herr,\r\nin dir ist Ruh.\r\nMit dir überwind ich weit\r\ndes Todes Macht!\r\nO Wort voller Seligkeit:\r\nEs ist vollbracht!\r\nO preist seiner Liebe Macht!\r\nPreist seiner Liebe Macht!\r\nPreist seiner Liebe Macht,\r\ndie uns erlöst!', '', '', '', '', '', '', '', '', '', '', '', ''),
(229, 'Nun hab ich Heil gefunden ', 5, 'Nun hab ich Heil gefunden \r\nin dir, o Jesu Christ, \r\nund bin mit dir verbunden, \r\nder du mein alles bist. \r\nJa, ich weiß es, ich bin dein, \r\nund du bist auf ewig mein. \r\nEher will ich nunmehr sterben, \r\nals von dir geschieden sein.', 'Wie konnt ich doch so lange, \r\no Jesu, dir entfliehn \r\nund widerstehn dem Drange, \r\nder mich zu dir wollt ziehn! \r\nJa, ich weiß es, ich bin dein, \r\nund du bist auf ewig mein. \r\nEher will ich nunmehr sterben, \r\nals von dir geschieden sein.', 'Wer kann die Lieb ermessen? \r\nO Jesu, welche Huld! \r\nVergeben und vergessen \r\nhast du all meine Schuld. \r\nJa, ich weiß es, ich bin dein, \r\nund du bist auf ewig mein. \r\nEher will ich nunmehr sterben, \r\nals von dir geschieden sein.', 'Wer will mich noch verdammen? \r\nIch fürchte kein Gericht; \r\ndein teures Blut und Namen, \r\no Jesu, für mich spricht. \r\nJa, ich weiß es, ich bin dein, \r\nund du bist auf ewig mein. \r\nEher will ich nunmehr sterben, \r\nals von dir geschieden sein.', 'Dich lass ich nunmehr walten, \r\ndir übergeb ich mich; \r\ndu wirst mich feste halten, \r\no Jesu, ewiglich. \r\nJa, ich weiß es, ich bin dein, \r\nund du bist auf ewig mein. \r\nEher will ich nunmehr sterben, \r\nals von dir geschieden sein.', '', '', '', '', '', '', '', '', '', ''),
(242, 'Mein Jesus, ich lieb dich', 3, 'Mein Jesus, ich lieb dich,ich weiß, du bist mein, \r\nverzicht auf der Sündebetörenden Schein. \r\nIch hab deine Gnadenoch nie recht geschätzt, \r\nwenn je ich dich liebte,mein Jesus, ist\'s jetzt.', 'Dich lieb ich, dochdu hast mich vordem geliebt, \r\ndein Mitleid am Kreuzemir alles vergibt. \r\nFür mich haben Dornendas Haupt dir verletzt, \r\nwenn je ich dich liebte,mein Jesus, ist\'s jetzt.', 'Drum will ich dich liebenim Leben, im Tod, \r\ndich preisen, solangemir Odem schenkt Gott, \r\nund rufen, ob michauch der Todesschweiß netzt: \r\nWenn je ich dich liebte,mein Jesus, ist\'s jetzt.', '', '', '', '', '', '', '', '', '', '', '', ''),
(244, 'Wenn Friede mit Gott meine Seele durchdringt', 4, 'Wenn Friede mit Gott meine Seele durchdringt, \r\nob Stürme auch drohen von fern, \r\nmein Herze im Glauben doch allezeit singt: \r\nMir ist wohl, mir ist wohl in dem Herrn!', 'Wenn Satan mir nachstellt und bange mir macht, \r\nso leuchtet dies Wort mir als Stern: \r\nMein Jesus hat alles für mich schon vollbracht; \r\nich bin rein durch das Blut meines Herrn!', 'Die Last meiner Sünde trug Jesus, das Lamm, \r\nund warf sie weit weg in die Fern; \r\ner starb ja für mich auch am blutigen Stamm; \r\nmeine Seele lobpreise den Herrn!', 'Nun leb ich in Christus für Christus allein; \r\nsein Wort ist mein leitender Stern. \r\nIn ihm hab ich Fried und Erlösung von Pein, \r\nmeine Seele ist selig im Herrn.', '', '', '', '', '', '', '', '', '', '', ''),
(245, 'Herr, ich bin dein', 5, 'Herr, ich bin dein!Voll Ehrfurcht darf ich\'s sagen. \r\nIn Freud und Leidführ mich nur dein Gebot! \r\nHab ich nur dich, so weichen alle Klagen. \r\nHerr, ich bin dein!\r\nHerr, ich bin dein!', 'Ich irrte einstauf finstern Zweifelswegen, \r\nim Herzen leer,hatt ich den Tod vor mir; \r\ndoch jetzt darf ichin deine Hand mich legen. \r\nHerr, ich bin dein!\r\nHerr, ich bin dein!', 'Wie hast du michso freundlich doch umfangen \r\nmit Liebe nur,mit süßer Zärtlichkeit; \r\ndrum will ich, Herr,auch ewig an dir hangen.\r\nHerr, ich bin dein!\r\nHerr, ich bin dein!', 'Da ich dich fand,hab alles ich gefunden, \r\ndurch Glauben wardmir dieses Glück zuteil; \r\nnun ruh ich sanft, o Herr,in deinen Wunden.\r\nHerr, ich bin dein!\r\nHerr, ich bin dein!', 'Wo ich auch magauf dieser Erde wallen, \r\no Heiland, dein, mein Gott,nur dein bin ich. \r\nUnd droben einst, in jenen Himmelshallen, \r\nHerr, bin ich dein,\r\nauf ewig dein!', '', '', '', '', '', '', '', '', '', ''),
(246, 'Hier ist mein Herz', 6, 'Hier ist mein Herz!\r\nMein Gott, ich geb es dir,\r\ndir, der es gnädig schuf.\r\nNimm es der Welt,\r\nmein Kind, und gib es mir!\r\nDies ist an mich dein Ruf.\r\nHier ist das Opfer meiner Liebe;\r\nich weih es dir aus treuem Triebe.\r\nHier ist mein Herz, hier ist mein Herz.', 'Hier ist mein Herz!\r\nO nimm es gnädig an,\r\nob ihm gleich viel gebricht.\r\nIch geb es dir,\r\nso gut ich‘s geben kann;\r\nverschmäh die Gabe nicht!\r\nEs ist mit böser Lust beflecket,\r\nmit Sünd erfüllt, mit Schuld bedecket,\r\nmein sündig Herz, mein sündig Herz.', 'Hier ist mein Herz,\r\ndas bisher steinern war,\r\nnun ist‘s ein fleischern Herz.\r\nEs legt sich dir\r\nmatt und zerbrochen dar,\r\nes fühlet Angst und Schmerz;\r\nes jammert bei der Last von Sünden,\r\nes seufzt: Wo soll ich Rettung finden?\r\nMein reuig Herz, mein reuig Herz.', 'Hier ist mein Herz!\r\nEs sucht in Christus Heil,\r\nes naht zum Kreuze hin\r\nund spricht: O Herr,\r\ndu bist mein Gut und Teil,\r\ndein Tod ist mein Gewinn.\r\nEs hat in des Erlösers Wunden\r\nTrost, Ruh und Seligkeit gefunden,\r\nmein gläubig Herz, mein gläubig Herz.', 'Hier ist mein Herz!\r\nGeist Gottes, schaff es rein\r\nund mach es gänzlich neu;\r\nweih es dir selbst\r\nzum heilgen Tempel ein,\r\nmach es im Guten treu.\r\nHilf, dass es stets nach Gott verlange,\r\nihn fürcht und lieb und an ihm hange,\r\nmein neues Herz, mein neues Herz.', 'Hier ist mein Herz!\r\nbewahr es, treuster Freund,\r\nvor aller Feinde List;\r\ngib, wenn der Tod,\r\nder letzte Feind, erscheint,\r\ndass es stark, gläubig ist.\r\nHilf mir, wenn meine Augen brechen,\r\ndies treue Wort froh zu dir sprechen:\r\nHier ist mein Herz! Hier ist mein Herz!', '', '', '', '', '', '', '', '', ''),
(248, 'Welch ein Freund ist unser Jesus', 3, 'Welch ein Freund ist unser Jesus,\r\no wie hoch ist er erhöht! \r\nEr hat uns mit Gott versöhnet\r\nund vertritt uns im Gebet. \r\nWer mag sagen und ermessen, \r\nwie viel Heil verloren geht, \r\nwenn wir nicht zu ihm uns wenden \r\nund ihn suchen im Gebet!', 'Wenn des Feindes Macht uns drohet \r\nund manch Sturm rings um uns weht, \r\nbrauchen wir uns nicht zu fürchten, \r\nstehn wir gläubig im Gebet. \r\nDa erweist sich Jesu Treue, \r\nwie er uns zur Seite steht \r\nals ein mächtiger Erretter, \r\nder erhört ein ernst Gebet.', 'Sind mit Sorgen wir beladen, \r\nsei es frühe oder spät, \r\nhilft uns sicher unser Jesus, \r\nfliehn zu ihm wir im Gebet. \r\nSind von Freunden wir verlassen \r\nund wir gehen ins Gebet, \r\no so ist uns Jesus alles: \r\nKönig, Priester und Prophet.', '', '', '', '', '', '', '', '', '', '', '', ''),
(252, 'Bis hierher hat mich Gott gebracht', 3, 'Bis hierher hat mich Gott gebracht\r\ndurch seine große Güte, \r\nbis hierher hat er Tag und Nacht\r\nbewahrt Herz und Gemüte, \r\nbis hierher hat er mich geleit\',\r\nbis hierher hat er mich erfreut, \r\nbis hierher mir geholfen.', 'Hab Lob und Ehre, Preis und Dank\r\nfür die bisherge Treue, \r\ndie du, o Gott, mir lebenslang\r\nbewiesen täglich neue; \r\nin mein Gedächtnis schreib ich an: \r\nDer Herr hat Großes mir getan, \r\nbis hierher mir geholfen.', 'Hilf fernerweit, mein treuster Hort, \r\nhilf mir zu allen Stunden,\r\nhilf mir an all und jedem Ort, \r\nhilf mir durch Jesu Wunden,\r\ndamit ich sag bis in den Tod: \r\nDurch Christi Blut hilft mir mein Gott, \r\ner hilft, wie er geholfen.', '', '', '', '', '', '', '', '', '', '', '', ''),
(258, 'Befiehl du deine Wege ', 12, 'Befiehl du deine Wege \r\nund was dein Herze kränkt \r\nder allertreusten Pflege \r\ndes, der den Himmel lenkt. \r\nDer Wolken, Luft und Winden \r\ngibt Wege, Lauf und Bahn, \r\nder wird auch Wege finden, \r\nda dein Fuß gehen kann.', 'Dem Herren musst du trauen, \r\nwenn dir\'s soll wohlergehn; \r\nauf sein Werk musst du schauen, \r\nwenn dein Werk soll bestehn. \r\nMit Sorgen und mit Grämen \r\nund mit selbsteigner Pein \r\nlässt Gott sich gar nichts nehmen, \r\nes muss erbeten sein.', 'Dein ewge Treu und Gnade, \r\no Vater, weiß und sieht,\r\nwas gut sei oder schade \r\ndem sterblichen Geblüt; \r\nund was du dann erlesen, \r\ndas treibst du, starker Held, \r\nund bringst zu Stand und Wesen, \r\nwas deinem Rat gefällt.', 'Weg hast du allerwegen, \r\nan Mitteln fehlt dir\'s nicht;\r\ndein Tun ist lauter Segen, \r\ndein Gang ist lauter Licht; \r\ndein Werk kann niemand hindern, \r\ndein Arbeit darf nicht ruhn,\r\nwenn du, was deinen Kindern \r\nersprießlich ist, willst tun.', 'Und ob gleich alle Teufel \r\nhier wollten widerstehn, \r\nso wird doch ohne Zweifel \r\nGott nicht zurückegehn; \r\nwas er sich vorgenommen \r\nund was er haben will, \r\ndas muss doch endlich kommen \r\nzu seinem Zweck und Ziel.\r\n', 'Hoff, o du arme Seele, \r\nhoff und sei unverzagt! \r\nGott wird dich aus der Höhle, \r\nda dich der Kummer plagt, \r\nmit großen Gnaden rücken; \r\nerwarte nur die Zeit, \r\nso wirst du schon erblicken \r\ndie Sonn der schönsten Freud.', 'Auf, auf, gib deinem Schmerze \r\nund Sorgen gute Nacht,\r\nlass fahren, was das Herze \r\nbetrübt und traurig macht;\r\nbist du doch nicht Regente, \r\nder alles führen soll,\r\nGott sitzt im Regimente \r\nund führet alles wohl.', 'Ihn, ihn lass tun und walten, \r\ner ist ein weiser Fürst \r\nund wird sich so verhalten, \r\ndass du dich wundern wirst, \r\nwenn er, wie ihm gebühret, \r\nmit wunderbarem Rat \r\ndas Werk hinausgeführet, \r\ndas dich bekümmert hat.', 'Er wird zwar eine Weile \r\nmit seinem Trost verziehn \r\nund tun an seinem Teile, \r\nals hätt in seinem Sinn \r\ner deiner sich begeben \r\nund solltst du für und für \r\nin Angst und Nöten schweben, \r\nals frag er nichts nach dir.', 'Wird\'s aber sich befinden, \r\ndass du ihm treu verbleibst, \r\nso wird er dich entbinden, \r\nda du\'s am mindsten gläubst; \r\ner wird dein Herze lösen \r\nvon der so schweren Last, \r\ndie du zu keinem Bösen \r\nbisher getragen hast.', 'Wohl dir, du Kind der Treue! \r\nDu hast und trägst davon \r\nmit Ruhm und Dankgeschreie \r\nden Sieg und Ehrenkron; \r\nGott gibt dir selbst die Palmen \r\nin deine rechte Hand, \r\nund du singst Freudenpsalmen \r\ndem, der dein Leid gewandt.', 'Mach End, o Herr, mach Ende\r\nmit aller unsrer Not;\r\nstärk unsre Füß und Hände\r\nund laß bis in den Tod\r\nuns allzeit deiner Pflege\r\nund Treu empfohlen sein,\r\nso gehen unsre Wege\r\ngewiß zum Himmel ein.', '', '', ''),
(310, 'Ich bin durch die Welt gegangen', 5, 'Ich bin durch die Welt gegangen, \r\nund die Welt ist schön und groß, \r\nund doch ziehet mein Verlangen \r\nmich weit von der Erde los.', 'Ich habe die Menschen gesehen, \r\nund sie suchen spät und früh, \r\nsie schaffen, sie kommen und gehen, \r\nund ihr Leben ist Arbeit und Müh.', 'Sie suchen, was sie nicht finden \r\nin Liebe und Ehre und Glück, \r\nund sie kommen belastet mit Sünden \r\nund unbefriedigt zurück.', 'Es ist eine Ruh vorhanden \r\nfür das arme, müde Herz;\r\nlaut sagt es in allen Landen: \r\nHier ist gestillet der Schmerz.', 'Es ist eine Ruh gefunden \r\nfür alle, fern und nah, \r\nin des Gotteslammes Wunden \r\nam Kreuze auf Golgatha.', '', '', '', '', '', '', '', '', '', ''),
(327, 'Wanke nicht, steh fest im Glauben', 2, 'Wanke nicht, steh fest im Glauben,\r\nob‘s auch dunkel scheint zur Zeit.\r\nLass dir nichts die Hoffnung rauben;\r\nglaub‘s, der Sieg ist nicht mehr weit,\r\nja, der Sieg, um den wir ringen\r\nglaubend wider Feindes Macht.\r\nSieh, der Heiland lässt‘s gelingen,\r\ner erscheinet bald mit Pracht.', 'Darum wache, steh im Glauben!\r\nLasse männlich stark dich sehn,\r\nso kann dir der Feind nichts rauben,\r\nund du wirst dann einmal stehn\r\nunter denen, die sich freuen,\r\nwenn der Heiland bricht herein,\r\num uns völlig zu erneuen.\r\nWelche Wonne wird dann sein!', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(332, 'Ein feste Burg ist unser Gott', 4, 'Ein feste Burg ist unser Gott,\r\neine gute Wehr und Waffen.\r\nEr hilft uns frei aus aller Not,\r\ndie uns jetzt hat betroffen.\r\nDer altböse Feind,\r\nmit Ernst er‘s jetzt meint;\r\ngroß Macht und viel Listsein \r\ngrausam Rüstung ist,\r\nauf Erd ist nicht seinsgleichen.', 'Mit unsrer Macht ist nichts getan,\r\nwir sind gar bald verloren;\r\nes streit‘ für uns der rechte Mann,\r\nden Gott hat selbst erkoren.\r\nFragst du, wer der ist?\r\nEr heißt Jesus Christ,\r\nder Herr Zebaoth,\r\nund ist kein andrer Gott;\r\ndas Feld muss er behalten.', 'Und wenn die Welt voll Teufel \r\nwärund wollt uns gar verschlingen,\r\nso fürchten wir uns nicht so sehr,\r\nes soll uns doch gelingen.\r\nDer Fürst dieser Welt,\r\nwie saur er sich stellt,\r\ntut er uns doch nicht;\r\ndas macht, er ist gericht‘;\r\nein Wörtlein kann ihn fällen.', 'Das Wort sie sollen lassen stahn\r\nund kein‘ Dank dazu haben.\r\nEr ist bei uns wohl auf dem Plan\r\nmit seinem Geist und Gaben.\r\nNehmen sie den Leib,\r\nGut, Ehr, Kind und Weib:\r\nLass fahren dahin,\r\nsie haben kein Gewinn,\r\ndas Reich muss uns doch bleiben.', '', '', '', '', '', '', '', '', '', '', ''),
(352, 'O selig Haus, wo man dich aufgenommen', 4, 'O selig Haus, wo man dich aufgenommen,\r\ndu wahrer Seelenfreund, Herr Jesu Christ,\r\nwo unter allen Gästen, die da kommen,\r\ndu der gefeiertste und liebste bist,\r\nwo aller Herzen dir entgegenschlagen\r\nund aller Augen freudig auf dich sehn,\r\nwo aller Lippen dein Gebot erfragen\r\nund alle deines Winks gewärtig stehn.', 'O selig Haus, wo Mann und Weib in einer,\r\nin deiner Liebe eines Geistes sind,\r\nals beide eines Heils gewürdigt, keiner\r\nim Glaubensgrunde anders ist gesinnt,\r\nwo beide unzertrennbar an dir hangen\r\nin Lieb und Leid, Gemach und Ungemach\r\nund nur bei dir zu bleiben stets verlangen\r\nan jedem guten wie am bösen Tag.', 'O selig Haus, wo man die lieben Kleinen\r\nmit Händen des Gebets ans Herz dir legt,\r\ndu Freund der Kinder, der sie als die Seinen\r\nmit mehr als Mutterliebe hegt und pflegt,\r\nwo sie zu deinen Füßen gern sich sammeln\r\nund horchen deiner süßen Rede zu\r\nund lernen früh dein Lob mit Freuden stammeln,\r\nsich deiner freun, du lieber Heiland, du.', 'O selig Haus, wo du die Freude teilest,\r\nwo man bei keiner Freude dein vergisst;\r\no selig Haus, wo du die Wunden heilest\r\nund aller Arzt und aller Tröster bist,\r\nbis jeder einst sein Tagewerk vollendet\r\nund bis sie endlich alle ziehen aus\r\ndahin, woher der Vater dich gesendet,\r\nins große, freie, schöne Vaterhaus.', '', '', '', '', '', '', '', '', '', '', ''),
(376, 'Herr Jesu Christ, dich zu uns wend', 4, 'Herr Jesu Christ, dich zu uns wend,\r\ndein\' Heilgen Geist du zu uns send,\r\nmit Hilf und Gnad er uns regier\r\nund uns den Weg zur Wahrheit führ.', 'Tu auf den Mund zum Lobe dein,\r\nbereit das Herz zur Andacht fein,\r\nden Glauben mehr, stärk den Verstand, \r\ndass uns dein Nam werd wohlbekannt,', 'bis wir singen mit Gottes Heer:\r\nHeilig, heilig ist Gott der Herr\r\n!und schauen dich von Angesicht\r\nin ewger Freud und selgem Licht.', 'Ehr sei dem Vater und dem Sohn,\r\ndem Heilgen Geist in einem Thron;\r\nder Heiligen Dreieinigkeit\r\nsei Lob und Preis in Ewigkeit.', '', '', '', '', '', '', '', '', '', '', ''),
(387, 'Ach bleib mit deiner Gnade', 6, 'Ach bleib mit deiner Gnade\r\nbei uns, Herr Jesu Christ, \r\ndass uns hinfort nicht schade\r\ndes bösen Feindes List.', 'Ach bleib mit deinen Worten\r\nbei uns, Erlöser wert,\r\nauf dass uns hier und dorten\r\nsei Güt und Heil beschert.', 'Ach bleib mit deiner Klarheit\r\nbei uns, du wertes Licht;\r\numgürt uns mit der Wahrheit,\r\ndamit wir irren nicht.', 'Ach bleib mit deinem Segen\r\nbei uns, du reicher Herr;\r\ndein Gnad und alls Vermögen\r\nin uns reichlich vermehr.', 'Ach bleib mit deinem Schutze\r\nbei uns, du starker Held,\r\ndass uns der Feind nicht trutze\r\nnoch fäll die böse Welt.', 'Ach bleib mit deiner Treue\r\nbei uns, mein Herr und Gott;\r\nBeständigkeit verleihe,\r\nhilf uns aus aller Not!', '', '', '', '', '', '', '', '', ''),
(388, 'Friede sei nun mit euch allen', 3, 'Friede sei nun mit euch allen,\r\ndie ihr bittend vor Gott steht;\r\ndenn mit Händen voller Segen\r\nChristus durch die Reihen geht,\r\nreichlich zu beschenken jeden,\r\nder um seinen Segen fleht.', 'Licht vom Licht, zu uns gekommen\r\naus der Welt der Ewigkeit,\r\nmach die Macht des Bösen schwinden,\r\nweichen alle Dunkelheit.\r\nZünde an in uns dein Feuer,\r\nmach uns selbst zum Dienst bereit.', 'Und am Ende dieser Tage\r\nlade uns zum Festmahl ein.\r\nLass uns mit der Schar der Deinen\r\nin dein Lob dann stimmen ein:\r\nHalleluja, halleluja,\r\nGott sei Preis, ihm Ehr allein!', '', '', '', '', '', '', '', '', '', '', '', ''),
(392, 'Lass mich dein sein und bleiben', 1, 'Lass mich dein sein und bleiben,\r\ndu treuer Gott und Herr,\r\nvon dir lass mich nichts treiben,\r\nhalt mich bei deiner Lehr.\r\nHerr, lass mich nur nicht wanken,\r\ngib mir Beständigkeit;\r\ndafür will ich dir danken\r\nin alle Ewigkeit.\r\n', '', '', '', '', '', '', '', '', '', '', '', '', '', ''),
(412, 'Die Hände, die sich falten', 4, 'Die Hände, die sich falten,\r\nruhn von der Sorge aus.\r\nWer in die Stille eintritt,\r\nkommt von weither nach Haus.\r\nDie Hände, die sich falten,\r\nlässt Gott ganz ruhig sein.\r\nWenn du die Hände faltest,\r\nbist du nicht mehr allein.', 'Warum machst du dir Sorgen,\r\nwo du doch beten kannst\r\nund damit, was dich umtreibt,\r\naus deinem Herzen bannst?\r\nWarum machst du dir Sorgen,\r\nwo Gott doch bei dir ist\r\nund wo in seinem Lichte\r\nden neuen Tag du siehst?', 'Das Beten ist die Quelle\r\nfür jedes rechte Tun.\r\nDarum lass vor der Arbeit\r\ndie Hände betend ruhn.\r\nDas Beten ist die Quelle,\r\naus der die Gnade quillt,\r\ndie durch der Beter Hände\r\nim Dienen sich erfüllt.', 'Die Hände, die sich falten,\r\nerschließen sich dem Leid.\r\nWas im Gebet dir aufgeht,\r\nmacht dir den Blick ganz weit.\r\nDu lebst, wo Gott dich segnet,\r\nja nie für dich allein.\r\nDer Beter wird als Tätere\r\nin Zeuge Jesu sein.', '', '', '', '', '', '', '', '', '', '', ''),
(443, 'Auf, denn die Nacht wird kommen', 3, 'Auf, denn die Nacht wird kommen,\r\nauf mit dem jungen Tag!\r\nWirket am frühen Morgen,\r\neh\'s zu spät sein mag!\r\nWirket im Licht der Sonnen,\r\nfanget beizeiten an!\r\nAuf, denn die Nacht wird kommen,\r\nda man nicht mehr kann!', 'Auf, denn die Nacht wird kommen,\r\nauf, wenn es Mittag ist!\r\nWeihet die besten Kräfte\r\ndem Herrn Jesus Christ!\r\nWirket mit Ernst, ihr Frommen,\r\ngebt alles andre dran!\r\nAuf, denn die Nacht wird kommen,\r\nda man nicht mehr kann!', 'Auf, denn die Nacht wird kommen,\r\nauf, wenn die Sonne weicht;\r\nauf, wenn der Abend mahnet,\r\nwenn der Tag entfleucht!\r\nAuf bis zum letzten Zuge,\r\nwendet nur Fleiß daran!\r\nAuf, denn die Nacht wird kommen,\r\nda man nicht mehr kann!', '', '', '', '', '', '', '', '', '', '', '', ''),
(586, 'Ich blicke voll Beugung und Staunen', 4, 'Ich blicke voll Beugung und Staunen\r\nhinein in das Meer seiner Gnad\r\nund lausche der Botschaft des Friedens,\r\ndie er mir verkündiget hat.\r\nSein Kreuz bedeckt meine Schuld.\r\nSein Blut macht hell mich und rein.\r\nMein Wille gehört meinem Gott,\r\nich traue auf Jesus allein.', 'Wie lang hab ich mühvoll gerungen,\r\ngeseufzt unter Sünde und Schmerz!\r\nDoch als ich mich ihm überlassen,\r\nda strömte sein Fried in mein Herz.\r\nSein Kreuz bedeckt meine Schuld.\r\nSein Blut macht hell mich und rein.\r\nMein Wille gehört meinem Gott,\r\nich traue auf Jesus allein.', 'Sanft hat seine Hand mich berühret;\r\ner sprach: O mein Kind, du bist heil!\r\nIch fasste den Saum seines Kleides,\r\nda ward seine Kraft mir zuteil.\r\nSein Kreuz bedeckt meine Schuld.\r\nSein Blut macht hell mich und rein.\r\nMein Wille gehört meinem Gott,\r\nich traue auf Jesus allein.', 'Der Fürst meines Friedens ist nahe;\r\nsein Antlitz ruht strahlend auf mir.\r\nO horcht seiner Stimme; sie rufet:\r\nden Frieden verleihe ich dir!\r\nSein Kreuz bedeckt meine Schuld.\r\nSein Blut macht hell mich und rein.\r\nMein Wille gehört meinem Gott,\r\nich traue auf Jesus allein.', '', '', '', '', '', '', '', '', '', '', ''),
(589, 'Herr, ich will nichts von Schätzen', 3, 'Herr, ich will nichts von Schätzen,\r\nnichts vom Reichtum der Welt;\r\nhab mein ganzes Verlangen\r\nauf den Himmel gestellt.\r\nLieber Heiland, o sag nur,\r\nob in Gnaden mein Nam\r\nauf ein Blatt deines Buches\r\nauch zu stehen schon kam!\r\nAuf dies eine, o Herr,\r\nwollst du gnädiglich sehn:\r\ndass im himmlischen Buche\r\nstets mein Name mög stehn!', 'Meine Sünden sind zahlreich\r\ngleich dem Sande am Meer;\r\ndoch dein Blut tut Genüge,\r\ngütger Heiland und Herr;\r\ndenn gar hell ich geschrieben\r\ndieses Wort vor mir seh:\r\nob die Sünde wie Scharlach,\r\nsoll sie werden wie Schnee!\r\nAuf dies eine, o Herr,\r\nwollst du gnädiglich sehn:\r\ndass im himmlischen Buche\r\nstets mein Name mög stehn!', 'O der lieblichen Stätte\r\nim herrlichen Land\r\nmit verklärten Bewohnern\r\nin weißem Gewand;\r\nda kein Übel gelanget\r\ndurch die heilige Pfort,\r\ndie von Engeln bewahret – \r\nsteht auch mein Name dort?\r\nAuf dies eine, o Herr,\r\nwollst du gnädiglich sehn:\r\ndass im himmlischen Buche\r\nstets mein Name mög stehn!', '', '', '', '', '', '', '', '', '', '', '', '');
INSERT INTO `songs` (`id`, `title`, `versnr`, `v1`, `v2`, `v3`, `v4`, `v5`, `v6`, `v7`, `v8`, `v9`, `v10`, `v11`, `v12`, `v13`, `v14`, `v15`) VALUES
(595, 'Ich hörte Jesu Freundesruf', 3, 'Ich hörte Jesu Freundesruf:\r\nKomm her, beladnes Herz,\r\nan meinem Herzen findst du Ruh\r\nfür allen deinen Schmerz.\r\nIch kam zu ihm, so wie ich war,\r\nbeladen, krank und matt,\r\nda schenkte er mir Fried und Ruh\r\naus freier Huld und Gnad!', 'Ich hörte Jesu Freundesruf:\r\nWer durstig ist, der komm,\r\nund wer kein Geld hat, trinke nur\r\numsonst vom Lebensstrom!\r\nIch kam zu Jesus, und ich trank\r\naus dieser heilgen Flut;\r\nda ward der Seele Durst gestillt,\r\nnun leb ich durch sein Blut.', 'Ich hörte Jesu Freundesruf:\r\nIch bin das Licht der Welt;\r\nin Finsternis blick auf zu mir,\r\nso wird dein Weg erhellt!\r\nIch schaute auf und fand in ihm\r\nden hellen Morgenstern\r\nund wandle nun in seinem Licht\r\nzur Heimat, zu dem Herrn.', '', '', '', '', '', '', '', '', '', '', '', ''),
(600, 'Seliges Wissen: Jesus ist mein!', 3, 'Seliges Wissen: Jesus ist mein!\r\nFrieden mit Gott bringt er mir allein.\r\nLeben von oben, ewiges Heil, \r\nvöllige Sühnung ward mir zuteil. \r\nLasst mich\'s erzählen, Jesus zur Ehr, \r\nwo ist ein Heiland wie unser Herr?\r\nWer kann so segnen, wer so erfreun? \r\nKeiner als Jesus. Preis ihm allein!', 'Ihm will ich leben - o welche Freud! \r\nHerrliche Gaben Jesus verleiht; \r\ngöttliche Leitung, Schutz in Gefahr, \r\nSieg über Sünde reicht er mir dar. \r\nLasst mich\'s erzählen, Jesus zur Ehr, \r\nwo ist ein Heiland wie unser Herr? \r\nWer kann so segnen, wer so erfreun? \r\nKeiner als Jesus. Preis ihm allein!', 'Völligen Frieden in aller Hast: \r\nJesus bewahrt mich, trägt meine Last. \r\nTreu will ich dienen ihm immerdar – \r\nbis er mich ruft zur oberen Schar.\r\nLasst mich\'s erzählen, Jesus zur Ehr, \r\nwo ist ein Heiland wie unser Herr? \r\nWer kann so segnen, wer so erfreun? \r\nKeiner als Jesus. Preis ihm allein!', '', '', '', '', '', '', '', '', '', '', '', '');

--
-- Indizes der exportierten Tabellen
--

--
-- Indizes für die Tabelle `songs`
--
ALTER TABLE `songs`
  ADD PRIMARY KEY (`id`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
